In [16]:
# Image to Numpy Array
#I take only 10 images and convert it into numpy array after resizing images you can check by running this code

import numpy as np
from PIL import Image
import os

for f in os.listdir('.'):
    if f.endswith('.jpg'):
        print(f)
        
        im = Image.open(f)
        #im.show()
        print(im)
        
        img=im.resize((200,200))
        img.show()
        
        img_np = np.zeros([10,200,200,3])
        
        print(img_np)  
        print(img_np.shape)

sk1.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=275x183 at 0x1C5B48C95F8>
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 2]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 2]
  [0 0 2]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 2]
  [0 0 2]
  [0 0 2]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(1200, 1920, 3)
sk10.jpg
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=300x168 at 0x1C5B48C9B00>
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 2]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 2]
  [0 0 2]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 2]
  [0 0 2]
  [0 0 2]
  ...
  [0 0 0]